### ISSUE TITLE
Package on Packagist website

### ISSUE THREAD

**Issue by Cronos87** [werdlv/ivona-speechcloud-sdk-php#1]
Hello!

Is it possible to put this package on [Packagist](https://packagist.org/) website to simplify the requirement with Composer?

Many thanks.

**Comment by jsakars** [comment]
@Cronos87 sure - https://packagist.org/packages/werd/ivona-speechcloud-sdk-php

**Comment by Cronos87** [comment]
Thank you @werdlv! It's perfect :)

Be careful of the composer cli command in the readme, you type composer twice.

**Comment by jsakars** [comment]
@Cronos87 fixed it. Also updated dependencies so You should be good to go with latest release 1.0.2 ;)

**Comment by Cronos87** [comment]
@werdlv It's ok for me. Great job with this package ;)
