### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by SourceCipher** [werdlv/ivona-speechcloud-sdk-php#2]
Installed composer, ran the code as mentioned but getting this when trying to run php file.
**Fatal error: Class 'Werd\Ivona\SpeechCloud' not found**

**Comment by jsakars** [comment]
@gwidaz I am guessing it's because You haven't included Your autoloading file. If You are using nothing but a bare Composer - take a look at [Autoloading](https://getcomposer.org/doc/01-basic-usage.md#autoloading)

**Comment by jsakars** [comment]
Closing as there was no reply for more then a week

**Comment by SourceCipher** [comment]
No reply for a week? I received this email 5 min ago..

**Comment by jsakars** [comment]
![issue](https://cloud.githubusercontent.com/assets/1607778/20392084/f71375b6-acde-11e6-8fb7-c2679c36fa24.png)

Based on my calendar - yes ;)

**Comment by SourceCipher** [comment]
Yes i can see that, I just received an email saying that this thread is
closed, never received with the original reply. Anyway i got my ivona
partly working with java. It will do for now. Thanks for your time
